ldelossa/litee.nvim

lua/calltree/lsp/util.lua
lua/calltree/ui.lua

previous to this commit the calltree buffer would attach active lsp
clients.
this was for an initial idea which never panned out, but also causes
issues as the LSP think the calltree buffer is a valid source file, it
is not.
additionally, this pr fixes a few bad variable references in ui.lua
w/r/t config.
closes: #2

lsp,ui: do not attach lsp clients

---

lua/calltree/tree.lua
lua/calltree/ui.lua
lua/calltree/ui/marshal.lua

to get around #10 each node in the tree now has a unique key.
marshaling the tree is updated to cache the node at all given lines every
time write_tree is called.
marshaling a line is greatly simplified and just looks at the cached now
to understand which node is being selected.
closes #10

tree: unique keys

---

lua/calltree/lsp/handlers.lua
lua/calltree/lsp/util.lua
lua/calltree/ui.lua
lua/calltree/ui/marshal.lua

after researching #10 a bit more I found that certain LSPs (gopls here)
provides more accurate symbol information via a workspace symbol query.
it would be nice to receieve the same symbol info regardless of the lsp
method being used. see: https://github.com/golang/go/issues/49690
this pr now resolves the workspace symbol for all call hierarchy items
placed into the tree.
this is a bit slower (with gopls anyway) on start, however I've found
that after some caching the results are snappy.

ui,tree: use workspace symbol if possible

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/ui/window.lua

closes #21
this commit adds default highlights to calltree.
all default highlights can be overwriten.
a config option "no_hls" is added to disable highlights all together.

themeing: provide default highlights

---

lua/calltree/ui/marshal.lua

closes #16
this commit changes the logic of marshaling a node to a UI line.
if we determine the file a symbol belongs too does not exist in the
current workspace we now use the "detail" field from the symbol if
possible.
if the "detail" field is nil we fall back to just providing the full
path to the file.

ui: use lsp detail if file is not in current workspace

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/ui/marshal.lua

this commit adds adds indentation guides and further padding between the
expanded/collapsed glyph and the symbol type icon/text.
this commit also fixes a bug where node.symbol was being checked instead
of node.call_hierarchy_item.
closes #24

ui: indentation improvemnts

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/handlers.lua
lua/calltree/lsp/handlers.lua
lua/calltree/lsp/util.lua

LSPs may return different results depending on the method being
requested.
for instance gopls will return no receiver name when a call hierarchy
request is made, but will when a workspace symbol request is made.
to work around this we make a workspace symbol request for each call
hierarchy item returned when a calltree is invoked.
this proved to be very slow when done sync so this commit makes it
async using lua coroutines.

perf: async symbol gathering

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/lsp/handlers.lua
lua/calltree/lsp/util.lua
lua/calltree/ui.lua
lua/calltree/ui/marshal.lua
lua/calltree/ui/window.lua

this commit adds the ability to treat all calltree ui elements as a
unified panel similar to other IDEs.
the unified panel consists of a persistent symbol and call tree and both
UIs will stick together when the unified panel is toggled open or
closed.
this is an opt in feature and using each component separately is still
possible.

ui: unified panel

---

lua/calltree/handlers.lua
lua/calltree/ui/buffer.lua
lua/calltree/ui/help_buffer.lua

this commit maps the arrow keys to resize commands for calltree ui
buffers.
a few bug fixes along th way as well.

ui: allow resizing via arrow keys

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/handlers.lua
lua/calltree/ui.lua
lua/calltree/ui/auto_highlights.lua
lua/calltree/ui/buffer.lua
lua/calltree/ui/marshal.lua
lua/calltree/ui/window.lua

this commit adds an option (defaults on) to auto highlight and auto move
the cursor to the selected symbol in the symbol tree.

ui: auto highlight symboltree

---

lua/calltree.lua
lua/calltree/lsp/handlers.lua
lua/calltree/lsp/util.lua
lua/calltree/ui.lua
lua/calltree/ui/auto_highlights.lua

this commit reworks the CTOpen and STOpen commands.
now calling these commands will open the respective UI and jump
directly into it.
calling the same command from inside the calltree ui window will jump
back to the window which invoked it.
this is very useful when "jumping over" split windows such that the
symboltree does not unintentionally update with the outline of a buffer
between the intended buffer and the symbol outline window.

ui: open directly to calltree ui elements

---

lua/calltree/ui.lua
lua/calltree/ui/buffer.lua
lua/calltree/ui/help_buffer.lua

this commit adds a keymap to all calltree ui buffers for closing the
element and jumping back to the window that invoked it (if it still
exists).
this is useful for workflows which do not use a unified panel but also
like to quickly hide the UI elements after browsing the call/symbol
tree.

workflow: add smart closing of UI elements

---

lua/calltree.lua
lua/calltree/lsp/handlers.lua
lua/calltree/ui.lua
lua/calltree/ui/marshal.lua

this commit implements tracking between source code and the symboltree
ui.
now, both the symboltree and the source code will track each other, such
that movement in one will update the other's cursor position and
auto highlights.

ui,symboltree: source code tracking

---

README.md
doc/calltree.txt
lua/calltree.lua
lua/calltree/lsp/handlers.lua
lua/calltree/tree/tree.lua
lua/calltree/ui.lua
lua/calltree/ui/buffer.lua
lua/calltree/ui/help_buffer.lua
lua/calltree/ui/window.lua

this commit reworks the idea of an optional unified panel as the idea
was getting messy.
now, the UI always acts as a unified panel, one which supports
permanently closing the symboltree or calltree if desired.
initial cleaning of the in-memory trees take place in this pr but more
cleaning, such as on tab delete, will take place in a subsequent pr.

usability: unified panel by default

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/tree/tree.lua
lua/calltree/ui.lua
lua/calltree/ui/buffer.lua

under certain conditions closing a tab can leave around unused tree
data structures.
by adding an autocommand that fires on TabClosed event we ensure any
tree data structures associated with the closed tabs are removed from memory on next lua gc.
closes #44 

tree: cleanup trees when tab closed

---

lua/calltree/lsp/handlers.lua
lua/calltree/ui.lua

previous to this commit if you opened the symboltree before opening a
calltree the calltree buffer would incorrectly be named "empty".

fix: empy buffer name fix

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/ui/buffer.lua

fix: resize keys for layout "bottom" were not bound correctly

feat: make mapping of cursor keys to resize optional

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/ui/buffer.lua
lua/calltree/ui/help_buffer.lua

this commit adds an au which hides the cursor when entering a
calltree.nvim window and unhides it when exiting.
this is driven by the "hide_cursor" option which defaults to false.

ui: hide cursor in calltree.nvim windows

---

doc/calltree.txt
lua/calltree.lua
lua/calltree/ui/marshal.lua
lua/calltree/ui/window.lua

this commit adds configurable highlights for indent guides, expanded
guides, and collapsed guides.

ui: add more highlights

---

lua/calltree/ui.lua
lua/calltree/ui/marshal.lua

this commit now displays "leafs" by removing any expanded guides for
calltree elements.
additionally, we now perform source code tracking bottom up in order to
handle nested elements correctly.

ui: display leafs and improve source tracking

---

README.md
lua/calltree/ui.lua
lua/calltree/ui/window.lua

Rationale behind this modification: I have bound a key to `toggle_panel()` but with recent changes this will no longer open the panel before I first called any of the LSP methods (before it just opened the symboltree and populated it).
With this change I can check if opening the panel was successful and if not call `vim.lsp.buf.document_symbol()` so it will eventually do what I want. ;-)

feat: let toggle_panel return wether or not it opened the panel

---

lua/litee/ui.lua

this commit ensures jumping (opening) to a file from the filetree will
do so in the last source file window focused before entering the
filetree.
this is done by continually updating "invoking_filetree_win" just before
setting the current window to the filetree itself.
it short circuits if the previous focused window is the filetree itself,
ensuring the jumped-to file will not open in the filetree window.

useability: make filetree jumps use the last window

---

doc/litee.txt

Generating help tags fails without this fix. Here's the script we use in NixOS:
https://github.com/NixOS/nixpkgs/blob/21.11/pkgs/misc/vim-plugins/vim-gen-doc-hook.sh
This duplicate tag was not present before the refactor:
https://github.com/ners/litee.nvim/blob/f208798a2f46ae8e31195a99ffa6e192782e59cb/doc/calltree.txt

Fix duplicate doc tag

---

doc/litee.txt
lua/litee/lib/commands.lua
lua/litee/lib/config.lua
lua/litee/lib/term/init.lua

lib term provides a "litee.nvim" aware terminal.
the term is Neovim's built in terminal emulator called with the $SHELL
variable as its attached process.
this is useful as spawning a term will not fight with any currently
open litee.panel instance.
see (h: litee-lib-term) for full details

feat,term: introduce lib term

---

lua/litee/lib/commands.lua
lua/litee/lib/jumps/init.lua
lua/litee/lib/panel/autocmds.lua
lua/litee/lib/panel/init.lua

this commit introduces a feature where panel components can be "popped
out" of the panel into a float on the lower right-hand side of the
editor.
a popout can occur both when the panel is closed and open. if a popout
is triggered when the panel is open the window is removed from the panel
and placed back into the panel when the "LTClosePanelPopOut" command is
issued.
if the panel is closed, it is transparently opened to generate all
component buffers and windows and the requested component window is made
into a float. the other windows are then closed.
a user could opt to use only popups and if they desire, all components
with active state will always be available when toggling the panel
regardless.

Popout Panels

---

lua/litee/lib/icons/init.lua

I was getting `Pattern delimiter not found: /[]/` errors in `gh.nvim` until i made these two changes in litee.
empty string (as opposed to space) and brackets creates problems for replacer function in window.lua

edit: escape icons

---

lua/litee/lib/jumps/init.lua
lua/litee/lib/lsp/init.lua
lua/litee/lib/tree/node.lua

1. last param of lsp client request method should be bufnr but not win
2. if `vim.lsp.util.jump_to_location` does not have `offset_encoding` param, it gives a warning

fix: wrong param of lsp client request and offset_encoding warning

---

lua/litee/lib/util/window.lua

When icons uses normal letters, like the 'simple' icon set for example, the highlight matching will also apply to all other instances of these icons, even within other words. Consider the case when 'Expanded' icon is set to 'v', then the underlined part of the example below will use same highlight as 'LTExpanded'
X some_symbol_with_v
~
This change makes icon symbol matching cover the entire words/tokens, instead of parts of

Fix: limit icon pattern to single token
